### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by KPull**
In this pull request we have:
1. The notifications feature branch.
2. The "Mark as Paid" feature.
3. Some significant UI changes. A new feature in particular is that the client will autofill the Price field for items input in an order. A removed feature is that I removed the "Hungry" box at the top as it was barely ever used and just acted as unnecessary clutter.

### CODE REVIEW

**Comment by camilleriluke** [comment]
When creating an order the client redirects to `/#/order/undefined`

Some comments:
- Keep PRs as single responsibility, the more concerns we add the the PRs the more risk that all the features will be blocked.
- Some of the updates in these pull requests (f.ex. UI change) haven't even been discussed in an issues. For the sake of transparency make sure that all updates to the code base reflect an issue. Also adding the issue number (like so: `camilleriluke/ejja-ha-nieklu#<number>`) to the commit message will link the commit to the issue

**Comment by KPull** [comment]
I do have the UI changes on a separate branch but I'm anticipating that the other pull requests will make it to the main branch so I got the conflict resolutions out of the way.

Also, changes which are not part of an issue are part of our ongoing effort to make the application better. As part of the refinement process do look at the proposed changes in this pull request and discuss any further improvements (or outright propose for its reversal).

I'll take a look at the redirection problem. It should redirect to the order the user just opened.

**Comment by KPull** [comment]
Pushed a fix for the incorrect redirect. It seems the MongoClient is returning a different object in its callbacks. Not sure what the deal was here.

**Comment by camilleriluke** [comment]
Tried to merge PR but site failed to load after `grunt build`. Please make sure that injected modules observe the obfuscation-safe pattern.

**Pull request merged**
