### PR TITLE
Split web.js into modules

### PR DESCRIPTION
**Pull request by KPull**
In this pull request, I split the web.js file into separate modules so that each REST resource has its own module.
I'm using the mocha tests developed earlier to make sure that all modules fully implement the expected API.
This pull request is not ready for merging yet.

### CODE REVIEW

**Comment by KPull** [comment]
I have finished splitting the Orders and Item resources into separate modules. Endpoints are tested using the associated tests as well.

**Comment by camilleriluke** [comment]
Run the following and let me know if it works for you. 
```shell
# assuming you are in the <ejja-ha-nieklu> dir
cd webapp
grunt build
cd ..
node web
# open http://localhost:5000/
```

I am getting ```Uncaught Error: [$injector:unpr] Unknown provider: aProvider <- a```

**Comment by KPull** [comment]
I've found the functions without the necessary injected dependencies. I'll be writing frontend tests soon so that we can automatically verify that the Angular app works.

**Comment by camilleriluke** [comment]
It's LIVE :rocket:! 

Nice one!

**Pull request merged**
